### ISSUE TITLE
Error trying to generate code : Uncaught exception 'InvalidArgumentException' with message 'Value() is null'

### ISSUE THREAD

**Issue by olivierbeytrison** [wsdl2phpgenerator/wsdl2phpgenerator#275]
I'm trying to generate a library from the Cisco AXL wsdl. But it fails with the following error

```
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Value() is null' in /wwwroot/standard-site/hefr.ch/uc/admin/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Enum.php:95
Stack trace:
#0 /wwwroot/standard-site/hefr.ch/uc/admin/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Generator.php(164): Wsdl2PhpGenerator\Enum->addValue('')
#1 [internal function]: Wsdl2PhpGenerator\Generator->Wsdl2PhpGenerator\{closure}('', 1)
#2 /wwwroot/standard-site/hefr.ch/uc/admin/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Generator.php(165): array_walk(Array, Object(Closure))
#3 /wwwroot/standard-site/hefr.ch/uc/admin/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Generator.php(108): Wsdl2PhpGenerator\Generator->loadTypes()
#4 /wwwroot/standard-site/hefr.ch/uc/admin/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Generator.php(89): Wsdl2PhpGenerator\Generator->load('AXL/AXLAPI.wsdl')
#5 /wwwroot/standard-site/hefr.ch/uc/admin/generate-wsdl.php(14): Wsdl2PhpGenerator\Generator->generate(Object(Wsdl2PhpGenerator\Config))
# in /wwwroot/standard-site/hefr.ch/uc/admin/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Enum.php on line 95
```

Upon request I can provide the wsdl + xsd files

**Comment by kasperg** [comment]
Apologies for the late reply. This issue is getting old.

If still relevant please reopen the issue and provide more information about the WSDL and XSDs you are trying to use - either as a link or by attaching them to this issue.

**Comment by skeagy** [comment]
[axl-wsdl-and-xsd.zip](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/files/551427/axl-wsdl-and-xsd.zip)

I have the exact same problem. Attached is the WSDL file (and referenced XSD files) that I am trying to parse.

**Comment by kasperg** [comment]
Thanks for the followup @skeagy.

The problem resides with the `XMOHAudioSourceId` type. It is defined as below. The enumeration value "" causes problems for [the Enum class](https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/src/Enum.php#L94).

```xml
    <xsd:simpleType name="XMOHAudioSourceId">
		<xsd:union>
			<xsd:simpleType>
				<xsd:restriction base="xsd:nonNegativeInteger">
					<xsd:minInclusive value="0"/>
					<xsd:maxInclusive value="51"/>
				</xsd:restriction>
			</xsd:simpleType>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="null"/>
					<xsd:enumeration value=""/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:union>
	</xsd:simpleType>
```
