### ISSUE TITLE
Return value of `iconv` not handled properly.

### ISSUE THREAD

**Issue by SamMousa** [wsdl2phpgenerator/wsdl2phpgenerator#317]
I tried to run the generator on Alpine Linux (which apparently has a bug in iconv).
````
private static function validateNamingConvention($name)
    {

        $name = iconv("UTF-8", "ASCII//TRANSLIT", $name);

        // Prepend the string a to names that begin with anything but a-z This is to make a valid name
        if (preg_match('/^[A-Za-z_]/', $name) == false) {
            $name = self::NAME_PREFIX . ucfirst($name);
        }

        return preg_replace('/[^a-zA-Z0-9_x7f-xff]*/', '', preg_replace('/^[^a-zA-Z_x7f-xff]*/', '', $name));
    }
````

If `iconv` fails it returns `false`, which is then cast to the empty string and thus an `a` is prepended.
This leads to a hard to debug error message.

**Comment by dmz9** [comment]
+1 to that. 
parsing cyrillic wsdl brings the same errors. at the end of validateNamingConvention i get 2 fatal uncaught errors like 

``
PHP Fatal error:  Uncaught Exception: No value supplied in ...\vendor\wsdl2phpgenerator\wsdl2phpgenerator\lib\PhpSource\PhpClass.php:238
Stack trace:
#0 ...\vendor\wsdl2phpgenerator\wsdl2phpgenerator\src\Enum.php(66): Wsdl2PhpGenerator\PhpSource\PhpClass->addConstant('', 'a')
#1 ...\vendor\wsdl2phpgenerator\wsdl2phpgenerator\src\Type.php(86): Wsdl2PhpGenerator\Enum->generateClass()
#2 ...\vendor\wsdl2phpgenerator\wsdl2phpgenerator\src\Generator.php(220): Wsdl2PhpGenerator\Type->getClass()
#3 ...\vendor\wsdl2phpgenerator\wsdl2phpgenerator\src\Generator.php(92): Wsdl2PhpGenerator\Generator->savePhp()
#4 ...\generate_sdk.php(8): Wsdl2PhpGenerator\Generator->generate(Object(Wsdl2PhpGenerator\Config))
#5 {main}
  thrown in ...\vendor\wsdl2phpgenerator\wsdl2phpgenerator\lib\PhpSource\PhpClass.php on line 238

**Comment by mnavon** [comment]
I commented the line:
$name = iconv("UTF-8", "ASCII//TRANSLIT", $name);
and it work'ed well.
My wsdl is cyrillic also
