### ISSUE TITLE
Empty enumeration value error

### ISSUE THREAD

**Issue by dmz9** [wsdl2phpgenerator/wsdl2phpgenerator#320]
For an empty simpleType enumeration value which is empty sdk throws fatal error

<xs:enumeration value=""/>
<xs:enumeration value="Male"/>
<xs:enumeration value="Female"/>

``
PHP Fatal error:  Uncaught Exception: No value supplied in ...\vendor\wsdl2phpgenerator\wsdl2phpgenerator\lib\PhpSource\PhpClass.php:238
Stack trace:
#0 ...\vendor\wsdl2phpgenerator\wsdl2phpgenerator\src\Enum.php(66): Wsdl2PhpGenerator\PhpSource\PhpClass->addConstant('', 'a')
#1 ...\vendor\wsdl2phpgenerator\wsdl2phpgenerator\src\Type.php(86): Wsdl2PhpGenerator\Enum->generateClass()
#2 ...\vendor\wsdl2phpgenerator\wsdl2phpgenerator\src\Generator.php(220): Wsdl2PhpGenerator\Type->getClass()
#3 ...\vendor\wsdl2phpgenerator\wsdl2phpgenerator\src\Generator.php(92): Wsdl2PhpGenerator\Generator->savePhp()
#4 ...\generate_sdk.php(8): Wsdl2PhpGenerator\Generator->generate(Object(Wsdl2PhpGenerator\Config))
#5 {main}
  thrown in ...\vendor\wsdl2phpgenerator\wsdl2phpgenerator\lib\PhpSource\PhpClass.php on line 238

**Comment by ddekleer** [comment]
I also had this problem, for now this can be fixed by commenting out the line `throw new Exception('No value supplied');` in `wsdl2phpgenerator/lib/PhpSource/PhpClass.php`.
