### ISSUE TITLE
 instance of stdClass given error with 7.x

### ISSUE THREAD

**Issue by simevo** [wsdl2phpgenerator/wsdl2phpgenerator#356]
Hi we have a service that works with PHP 5.6, with 7.0 and 7.2 we get:
```
PHP Fatal error:  Uncaught SoapFault exception: [SOAP-ENV:Server] Argument 1 passed to SdIRiceviFileHandler::RiceviFile() must be an instance of fileSdIBase_Type, instance of stdClass given in .../SdIRiceviFile_service.php:43
Stack trace:
#0 .../SdIRiceviFile_service.php(43): SoapClient->__soapCall('RiceviFile', Array)
#1 .../test.php(14): Simevo\SdIRiceviFile_service->RiceviFile(Object(Simevo\fileSdIBase_Type))
#2 {main}
  thrown in /root/fatturapa-testsdi/SdIRiceviFile/SdIRiceviFile_service.php on line 43
```

any idea ?

**Comment by michcald** [comment]
I have the same issue when trying to upgrade to PHP 7

Has anyone sorted it?

**Comment by erjotek** [comment]
Workaround: remove type hinting from methods used by soapserver, because it's few years old php bug.

https://bugs.php.net/bug.php?id=54684
https://bugs.php.net/bug.php?id=60077

**Comment by gisostallenberg** [comment]
@simevo do you still experience the same with current master?
