### ISSUE TITLE
fails to honour context settings (Specifically for SSL)

### ISSUE THREAD

**Issue by ericol** [wsdl2phpgenerator/wsdl2phpgenerator#413]
When I tried to generate the classes from a WSDL with some specifict SSL settings (Custom certificate and verification disabled:
```PHP
$context = stream_context_create(array(
    'http' => array( 'user_agent' => 'MyPHPSoapClient' ),
    'ssl' => [
        // set some SSL/TLS specific options
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    ]
));

$options = array(
    'local_cert' => 'local.pem',
    'stream_context' => $context
);

```
Executing the code fails:
```
Warning: DOMDocument::load(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /home/symfony/projects/soap-client/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Xml/SchemaDocument.php on line 63

Warning: DOMDocument::load(): Failed to enable crypto in /home/symfony/projects/soap-client/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Xml/SchemaDocument.php on line 63

Warning: DOMDocument::load(<WSDL_REDACTED>): failed to open stream: operation failed in /home/symfony/projects/soap-client/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Xml/SchemaDocument.php on line 63

Warning: DOMDocument::load(): I/O warning : failed to load external entity "<WSDL_REDACTED>" in /home/symfony/projects/soap-client/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Xml/SchemaDocument.php on line 63

Fatal error: Uncaught Exception: Unable to load XML from <WSDL_REDACTED> in /home/symfony/projects/soap-client/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Xml/SchemaDocument.php:65
Stack trace:
#0 /home/symfony/projects/soap-client/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Xml/WsdlDocument.php(52): Wsdl2PhpGenerator\Xml\SchemaDocument->__construct(Object(Wsdl2PhpGenerator\Config), '<WSDL_REDACTED>')
#1 /home/symfony/projects/soap-client/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Generator.php(104): Wsdl2PhpGenerator\Xml\WsdlDocument->__construct(Object(Wsdl2PhpGenerator\Config), '<WSDL_REDACTED>')
#2 /home/symfony/projects/soap-client/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Generator.php(89): Wsdl2PhpGenerator\Generator->load('<WSDL_REDACTED>')
#3 /home/symfony/projects/soap-client/build.php(27): Wsdl2PhpGenerator\Generator->generate(Object(Wsdl2PhpGenerator\Config))
#4 {main}
  thrown in /home/symfony/projects/soap-client/vendor/wsdl2phpgenerator/wsdl2phpgenerator/src/Xml/SchemaDocument.php on line 65
```

The problem is that the context generated here:
https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/c92d01beed99b26b75d8c514f386f39eb84454c1/src/Xml/SchemaDocument.php#L52-L55

Fails to acknowledge the previous settings.
I fixed it by modifying the first lines of `StreamContextFactory::create` from this:
https://github.com/wsdl2phpgenerator/wsdl2phpgenerator/blob/master/src/StreamContextFactory.php#L22-L26
To this:
```PHP
    public function create(ConfigInterface $config)
    {

        $soapOptions = $config->get('soapClientOptions');

        if(isset($soapOptions['stream_context'])) {
            $options = stream_context_get_options($soapOptions['stream_context']);
        } else {
            $options = array();
        }
        $headers = array();
```

**Comment by ericol** [comment]
**Note**: The error lines above might differ from your own testings, because I did modify the files for debugging.
